### PR TITLE
Use puppetlabs standard for storing facts.

### PR DESCRIPTION
**Pull request by clburlison**
By storing these facts in the recommend directory structure people can use this repo without modification using tools like [r10k](https://github.com/puppetlabs/r10k).

### CODE REVIEW

**Comment by erikng** [comment]
Perhaps I am misunderstanding facts, but Graham told me that that directory would only work for facts utilizing puppet. By moving them here, you will need puppet as well. Is this incorrect?

**Comment by clburlison** [comment]
Nope puppet is not needed. 

If you are manually distributing these facts via a package like [this](https://github.com/salopensource/grahamgilbert-plugins/tree/master/encryption/facts-package) to `/usr/local/sal/facter/` then the only modification would be changing your package creation tool to look for a different directory in this repo.

However by using the `/lib/facter/` structure people whom are using puppet can use a feature called pluginsync to copy facts directory from your repo to `/var/lib/puppet/lib/facter/`. 

Does that clarify the change?

**Comment by erikng** [comment]
Oh I see what you mean.

So the real reason I did this was for sorting facts on my repo. I had thought that I may make facts that aren't "munki" ones and would through them into another folder inside of this folder structure.

Are you opposed to having a makefile/pkg posted instead?

**Comment by clburlison** [comment]
Kind of. I don't want to come off as being pushy and I understand your reasoning for sorting the facts that way. 

Most use a naming scheme like "os_service_FactDescription.rb" for their facts, as you are already mostly doing. I would recommend naming your facts "mac_munki_XXX" as these are limited to Darwin. The naming scheme is what most are using for organizing files. 

The main reason for this change would be allowing the use of puppet's build in tools. If you're still opposed I can always just copy your files manually.

I believe a makefile/pkg would be of benefit to others not using puppet however those using facter without puppet are definitely in the minority. :smiley:

**Comment by clburlison** [comment]
Closing old PRs/Issues.

**Comment by erikng** [comment]
I forgot about this. :)

**Pull request closed without merging**
